config/routes.rb
Rails.application.routes.draw do
  resources :cities
  root 'cities#index'

end

app/models/city.rb
class City < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/iconic_helper.rb
module IconicHelper
  def iconic_tag(glyph, size = 'sm')
    src = image_path("iconic/#{glyph}-#{size}.svg")

    tag('img', class: "iconic", data: { src: src })
  end
end

app/views/cities/_city.html.slim
.card
	.card__photo
		img src="https://d23ibjsass4npx.cloudfront.net//images/cities/cards/000/000/007/portrait/antwerpen.jpg?1404466032"
	.card__content
		h4 = link_to city.name, city
		p = city.content
		= iconic_tag('envelope-open', 'md')

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<form>
  <label><input type="radio" name="mode" value="grouped" checked> Aantallen</label>
  <label><input type="radio" name="mode" value="stacked"> Bedragen</label>
	<a href="#" class="test">Test</a>
</form>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @city.content %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proof</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>
<div class="cases-graph"></div>


</body>
</html>